
// lib/developers-data.ts
// Place this file at: lib/developers-data.ts
// Both your listing page AND [slug] page import from here

export interface Developer {
  id: string;       // matches the URL slug exactly
  name: string;
  coverImage: string;
  logo: string;
  logoIsText?: boolean;
  description: string;   // short — used on listing cards
  longDescription: string; // full — used on detail page
  developer: string;
  location: string;
  propertyTypes: string[];
  marketPosition: string[];
  href: string;
}

export const developers: Developer[] = [
  {
    id: "downtown-dubai",
    name: "Downtown Dubai",
    coverImage: "/developers/downtown.jpeg",
    logo: "/developers/downtownlogo.png",
    developer: "Emaar",
    location: "Dubai",
    description: "Developed by Emaar, Downtown Dubai is a flagship mixed-use master community and home to Burj Khalifa, Dubai Mall, and Dubai Opera. A prime luxury residential and commercial hub with strong rental demand and global investor appeal.",
    longDescription: "Downtown Dubai is Emaar's flagship mixed-use master community and one of the most iconic urban destinations in the world. Home to the Burj Khalifa — the tallest building on Earth — as well as The Dubai Mall, Dubai Opera, and the famous Dubai Fountain, this community blends luxury residential living with world-class retail, dining, and entertainment. Offering unrivalled connectivity and a prestigious address, Downtown Dubai continues to attract high-net-worth investors and residents seeking the pinnacle of urban lifestyle in the Middle East.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/downtown-dubai",
  },
  {
    id: "dubai-sports-city",
    name: "Dubai Sports City",
    coverImage: "/developers/dubaisportcity.webp",
    logo: "/developers/dubaisportscity-logo.png",
    developer: "Various",
    location: "Dubai",
    description: "A freehold master development built around sports and lifestyle facilities, offering apartments, townhouses, and villas with golf and academy facilities.",
    longDescription: "Dubai Sports City is a unique freehold master development purpose-built around world-class sporting infrastructure. Home to the Els Club Golf Course, ICC Global Cricket Academy, and multiple stadiums and sports academies, it attracts active residents and sports enthusiasts. The community offers a wide range of apartments, townhouses, and villas at competitive price points, making it popular with families and investors seeking strong rental yields in a lifestyle-oriented environment.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/dubai-sports-city",
  },
  {
    id: "arjan",
    name: "Arjan",
    coverImage: "/developers/arjan.jpg",
    logo: "",
    logoIsText: true,
    developer: "Various",
    location: "Dubailand",
    description: "Located in Dubailand, Arjan is a growing residential district offering mid-rise apartment communities with retail, parks, and proximity to Miracle Garden.",
    longDescription: "Arjan is a rapidly developing residential district nestled within Dubailand, positioned along Umm Suqeim Road. Known for its proximity to Dubai Miracle Garden and Butterfly Garden, the community features a variety of mid-rise apartment buildings from multiple developers. It offers excellent value for investors and end-users alike, with a growing retail and dining scene, landscaped parks, and easy access to major arterial roads connecting to key business districts across Dubai.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/arjan",
  },
  {
    id: "jvc",
    name: "JVC",
    coverImage: "/developers/jvc.webp",
    logo: "/developers/jvc-logo.png",
    developer: "Nakheel",
    location: "Dubai",
    description: "Jumeirah Village Circle is a centrally located family community featuring apartments, townhouses, and villas known for affordability and strong rental yields.",
    longDescription: "Jumeirah Village Circle (JVC) is one of Dubai's most popular and centrally located residential communities, developed by Nakheel. Offering an excellent mix of apartments, townhouses, and villas at accessible price points, JVC is highly sought after by families and young professionals. The community is renowned for its consistently high rental yields, circular layout with green spaces and parks, and strategic location providing easy access to major highways including Sheikh Mohammed Bin Zayed Road and Al Khail Road.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/jvc",
  },
  {
    id: "dubai-silicon-oasis",
    name: "Dubai Silicon Oasis",
    coverImage: "/developers/dubaisilicon.jpeg",
    logo: "/developers/dubaisilicon-logo.jpeg",
    developer: "Government of Dubai",
    location: "Dubai",
    description: "A government-owned technology park and free zone offering residential and commercial developments popular among professionals and SMEs.",
    longDescription: "Dubai Silicon Oasis (DSO) is a government-owned integrated technology park and free zone authority combining a modern residential community with a thriving commercial ecosystem. Home to numerous technology companies, startups, and SMEs, DSO offers a self-contained live-work-play environment complete with schools, retail, dining, and recreational facilities. Its free zone status, combined with affordable property prices and strong infrastructure, makes it a highly attractive address for tech professionals and investors seeking steady rental income.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/dubai-silicon-oasis",
  },
  {
    id: "meydan",
    name: "Meydan",
    coverImage: "/developers/mayden.jpg",
    logo: "/developers/meydan-logo.png",
    developer: "Meydan Group",
    location: "Dubai",
    description: "A premium mixed-use development anchored by Meydan Racecourse offering high-end villas and residences close to Downtown Dubai.",
    longDescription: "Meydan is a prestigious premium mixed-use development anchored by the world-famous Meydan Racecourse, host of the Dubai World Cup. Positioned just minutes from Downtown Dubai, the community offers high-end villas, townhouses, and luxury residences within a beautifully landscaped environment. With the Meydan Hotel, a golf course, retail boulevard, and marina, residents enjoy an unparalleled lifestyle. Meydan's proximity to key business hubs and its upscale atmosphere make it a magnet for discerning buyers and investors.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/meydan",
  },
  {
    id: "sobha-hartland-1",
    name: "Sobha Hartland 1",
    coverImage: "/developers/sobha.jpeg",
    logo: "/developers/soba-logo.webp",
    developer: "Sobha Realty",
    location: "MBR City, Dubai",
    description: "A luxury waterfront community by Sobha Realty in MBR City featuring villas and premium apartments surrounded by green spaces.",
    longDescription: "Sobha Hartland is a luxury waterfront community developed by Sobha Realty within Mohammed Bin Rashid City. Spanning over 8 million sq ft, it is a meticulously master-planned neighbourhood featuring premium villas, townhouses, and high-rise apartments set amidst 30% green space including two international schools, a clubhouse, and direct access to the Dubai Canal. Sobha's trademark backward integration model ensures exceptional quality control from construction to finishing, making Hartland one of Dubai's most trusted luxury addresses.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/sobha-hartland-1",
  },
  {
    id: "sobha-hartland-2",
    name: "Sobha Hartland 2",
    coverImage: "/developers/soba2.webp",
    logo: "/developers/soba2-logo.webp",
    developer: "Sobha Realty",
    location: "MBR City, Dubai",
    description: "An extension of the Hartland master plan offering waterfront residences and modern high-rise living in Mohammed Bin Rashid City.",
    longDescription: "Sobha Hartland 2 is the next chapter of Sobha Realty's flagship master development in Mohammed Bin Rashid City. Building on the success of Hartland 1, this extension brings a fresh wave of waterfront residences and contemporary high-rise towers to one of Dubai's most sought-after corridors. Residents benefit from lush green landscapes, private lagoons, and seamless connectivity to Downtown Dubai — all delivered with Sobha's hallmark quality and attention to detail.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/sobha-hartland-2",
  },
  {
    id: "azizi-riviera",
    name: "Azizi Riviera",
    coverImage: "/developers/azizi.jpeg",
    logo: "/developers/azizi-logo.png",
    developer: "Azizi Developments",
    location: "Meydan, Dubai",
    description: "A French-Mediterranean inspired waterfront community in Meydan developed by Azizi, offering residential apartments and retail boulevard lifestyle.",
    longDescription: "Azizi Riviera is a large-scale French-Mediterranean inspired waterfront community located in the heart of Meydan, Dubai. Comprising over 70 mid-rise residential buildings, a mega retail boulevard, and a stunning crystal lagoon, Riviera seamlessly blends European elegance with modern Dubai living. The development features an array of studio, one, two, and three-bedroom apartments catering to a wide spectrum of buyers. Its vibrant retail and dining promenade creates a resort-like atmosphere that draws both residents and visitors.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/azizi-riviera",
  },
  {
    id: "azizi-venice",
    name: "Azizi Venice",
    coverImage: "/developers/azizivenice.webp",
    logo: "/developers/azizivenice-logo.png",
    developer: "Azizi Developments",
    location: "Dubai South",
    description: "A waterfront master development in Dubai South featuring lagoon living, residential towers, and mixed-use spaces.",
    longDescription: "Azizi Venice is a breathtaking waterfront master development located in Dubai South, inspired by the romance and architecture of Venice, Italy. The community is centred around a stunning 18 km crystal lagoon — the largest in Dubai — flanked by residential towers, townhouses, a hotel, and a vibrant retail and entertainment boulevard. Positioned near Al Maktoum International Airport and Expo City Dubai, Azizi Venice represents a compelling investment opportunity with strong capital appreciation potential.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/azizi-venice",
  },
  {
    id: "dubai-creek-harbour",
    name: "Dubai Creek Harbour",
    coverImage: "/developers/dubaicreek.jpeg",
    logo: "/developers/dubaicreek-logo.png",
    developer: "Emaar",
    location: "Ras Al Khor, Dubai",
    description: "A mega waterfront community by Emaar near Ras Al Khor, featuring Creek Beach and luxury high-rise developments.",
    longDescription: "Dubai Creek Harbour is Emaar's ambitious mega waterfront destination located adjacent to the Ras Al Khor Wildlife Sanctuary. Spanning 6 sq km of waterfront land, this landmark development will eventually be home to the Dubai Creek Tower, along with Creek Beach, the Island District, and a vibrant retail and dining promenade. With panoramic views of the Dubai skyline and nature reserve, Creek Harbour offers an exceptional blend of urban energy and natural serenity.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/dubai-creek-harbour",
  },
  {
    id: "dubai-hills-estate",
    name: "Dubai Hills Estate",
    coverImage: "/developers/dubaihills.jpeg",
    logo: "/developers/dubai-hills-logo.png",
    developer: "Emaar",
    location: "Dubai",
    description: "A master-planned community by Emaar featuring villas, townhouses, and apartments centered around a championship golf course.",
    longDescription: "Dubai Hills Estate is one of Emaar's most prestigious master-planned communities. Centred around an 18-hole championship golf course, this sprawling development offers an exceptional mix of luxury villas, townhouses, and high-rise apartments. Dubai Hills Mall sits at the heart of the community alongside an extensive network of parks, cycling tracks, and walking trails. Its prime location between Downtown Dubai and Dubai Marina makes it one of the most desirable addresses in the city.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/dubai-hills-estate",
  },
  {
    id: "damac-hills",
    name: "DAMAC Hills",
    coverImage: "/developers/damac.jpg",
    logo: "/developers/damac-logo.webp",
    developer: "DAMAC Properties",
    location: "Dubai",
    description: "A gated golf community by DAMAC offering villas, townhouses, and apartments around Trump International Golf Club.",
    longDescription: "DAMAC Hills is a prestigious gated golf community developed by DAMAC Properties, built around the Trump International Golf Club Dubai. This self-contained community features luxury villas, townhouses, and apartments set amongst manicured greens and water features. Home to over 4,000 families, DAMAC Hills offers a full suite of amenities including a clubhouse, sports facilities, stables, skate park, and retail outlets.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/damac-hills",
  },
  {
    id: "damac-hills-2",
    name: "DAMAC Hills 2",
    coverImage: "/developers/damac2.webp",
    logo: "/developers/damac2-logo.webp",
    developer: "DAMAC Properties",
    location: "Dubai",
    description: "A master development offering affordable villas and townhouses with themed clusters and recreational amenities.",
    longDescription: "DAMAC Hills 2 — formerly known as Akoya Oxygen — is DAMAC's second master golf community, offering more affordable villas and townhouses set around a Trump World Golf Club. The community is divided into unique themed clusters inspired by cities and landscapes from around the world. With expansive parks, a water park, sports courts, retail spaces, and schools all within the development, DAMAC Hills 2 is ideal for families seeking a complete suburban lifestyle at a competitive price point.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/damac-hills-2",
  },
  {
    id: "damac-lagoons",
    name: "DAMAC Lagoons",
    coverImage: "/developers/lagoos.jpg",
    logo: "/developers/lagoos-logo.png",
    developer: "DAMAC Properties",
    location: "Dubai",
    description: "A Mediterranean-inspired villa community by DAMAC featuring lagoon water features and resort-style living.",
    longDescription: "DAMAC Lagoons is an extraordinary Mediterranean-inspired villa community by DAMAC Properties. Each cluster draws inspiration from a different Mediterranean destination — from Santorini and Venice to Costa Brava and Malta — complete with crystal lagoons, sandy beaches, and resort-style amenities. Offering 4 to 7-bedroom villas and townhouses, DAMAC Lagoons delivers a unique holiday-at-home lifestyle in one of Dubai's most visually stunning residential developments.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/damac-lagoons",
  },
  {
    id: "emaar-the-valley",
    name: "Emaar The Valley",
    coverImage: "/developers/valley.jpg",
    logo: "/developers/valley-logo.png",
    developer: "Emaar",
    location: "Dubai–Al Ain Road",
    description: "A suburban master community by Emaar offering modern townhouses with green landscapes and family-focused amenities.",
    longDescription: "Emaar The Valley is a thriving suburban master community located along the Dubai–Al Ain Road. Designed around the concept of natural living, the community features modern 3 and 4-bedroom townhouses set amidst golden beaches, a town centre, and expansive green lawns. Family-friendly amenities including a splash pad, sports facilities, and community gardens make The Valley an ideal choice for growing families seeking space and nature at accessible price points.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/emaar-the-valley",
  },
  {
    id: "emaar-arabian-ranches",
    name: "Emaar Arabian Ranches",
    coverImage: "/developers/emaar.jpeg",
    logo: "/developers/emaar-logo.png",
    developer: "Emaar",
    location: "Dubai",
    description: "An established villa community by Emaar known for golf courses, equestrian facilities, and premium suburban living.",
    longDescription: "Emaar Arabian Ranches is one of Dubai's most established and beloved villa communities, having set the benchmark for suburban living since its launch in the early 2000s. Centred around the Arabian Ranches Golf Club and Dubai Polo & Equestrian Club, the community offers generously sized villas and townhouses in a tranquil, tree-lined setting. With three phases catering to a wide range of buyers, Arabian Ranches remains a premium family lifestyle destination away from the city bustle.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/emaar-arabian-ranches",
  },
  {
    id: "al-marjan-island",
    name: "Al Marjan Island",
    coverImage: "/developers/al.jpg",
    logo: "/developers/al-logo.jpg",
    developer: "RAK Properties",
    location: "Ras Al Khaimah",
    description: "A waterfront island development in Ras Al Khaimah featuring resorts, residential towers, and hospitality investments.",
    longDescription: "Al Marjan Island is a stunning man-made archipelago off the coast of Ras Al Khaimah, rapidly emerging as one of the Northern Emirates' most exciting waterfront destinations. Home to luxury resorts, beachfront residential towers, and the eagerly anticipated Wynn Al Marjan Island — the UAE's first integrated resort — the island is drawing significant global investor attention. With pristine beaches and a growing hospitality ecosystem, Al Marjan Island offers compelling capital appreciation prospects.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/al-marjan-island",
  },
  {
    id: "sharjah",
    name: "Sharjah",
    coverImage: "/developers/sharjah.jpg",
    logo: "",
    logoIsText: true,
    developer: "Various",
    location: "Sharjah",
    description: "A cultural and residential emirate offering affordable housing options and strong rental demand near Dubai.",
    longDescription: "Sharjah is the UAE's cultural capital and a thriving residential emirate offering some of the most affordable property options in the region. With its proximity to Dubai — just 15–20 minutes from key business districts — Sharjah attracts a large population of professionals and families seeking spacious homes at a fraction of Dubai prices. Areas such as Aljada, Tilal City, and Maryam Island are transforming the emirate's real estate landscape with modern master developments.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/sharjah",
  },
  {
    id: "ajman",
    name: "Ajman",
    coverImage: "/developers/ajman.jpeg",
    logo: "/developers/ajman-logo.png",
    developer: "Various",
    location: "Ajman",
    description: "An emerging residential market offering affordable apartments and villas with growing infrastructure.",
    longDescription: "Ajman is one of the UAE's most affordable real estate markets and an emerging destination for value-driven investors and homebuyers. As the smallest of the seven emirates, Ajman offers surprisingly generous living spaces at highly competitive prices. Growing infrastructure investment, new master developments along the Ajman Corniche, and strong rental demand from Dubai commuters are steadily driving capital appreciation across the emirate.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/ajman",
  },
];

export function getDeveloperBySlug(slug: string): Developer | undefined {
  return developers.find((d) => d.id === slug);
}