// lib/developers-data.ts

export interface ProjectItem {
  name: string;
  image?: string;
  type?: string;
  status?: "Off-Plan" | "Ready" | "Under Construction";
  price?: string;
  beds?: string;
  baths?: string;
  size?: string;
  description?: string;
  highlights?: string[];
}

export interface Developer {
  id: string;
  name: string;
  coverImage: string;
  logo: string;
  logoIsText?: boolean;
  description: string;
  longDescription: string;
  developer: string;
  location: string;
  propertyTypes: string[];
  marketPosition: string[];
  href: string;
  projects?: ProjectItem[];
  contact?: {
    email: string;
    phone: string;
    whatsapp: string;
  };
}

export const developers: Developer[] = [
  {
    id: "emaar-properties",
    name: "Emaar Properties",
    coverImage: "/developers/emaar.jpg",
    logo: "/developers/emaar-logo.png",
    logoIsText: false,
    developer: "Emaar Properties",
    location: "Dubai, UAE",
    description: "Emaar Properties is one of the world's most valuable and admired real estate development companies, known for iconic landmarks like Burj Khalifa and Dubai Mall.",
    longDescription: "Emaar Properties is one of the most valuable and admired real estate development companies globally. As the developer behind the world's tallest building, the Burj Khalifa, and the world's largest mall, The Dubai Mall, Emaar has redefined the concept of luxury urban living. Founded in 1997 and listed on the Dubai Financial Market, Emaar has delivered over 99,000 residential units since inception across the UAE and international markets. Their master communities include Downtown Dubai, Dubai Hills Estate, Arabian Ranches, Emaar Beachfront, and Dubai Creek Harbour, each setting benchmarks for lifestyle, architecture, and long-term investment value.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/emaar-properties",
    projects: [
      {
        name: "Downtown Dubai – The Address Residences",
        image: "/developers/downtown.jpeg",
        type: "Apartment",
        status: "Ready",
        price: "From AED 2,500,000",
        beds: "1–4 Beds",
        baths: "1–4 Baths",
        size: "700–4,500 sqft",
        description: "Iconic luxury residences in the heart of Downtown Dubai, offering stunning views of Burj Khalifa and Dubai Fountain.",
        highlights: ["Burj Khalifa Views", "Steps from Dubai Mall", "World-class amenities", "High ROI area"],
      },
      {
        name: "Dubai Hills Estate – Park Lane",
        image: "/developers/dubaihills.jpeg",
        type: "Villa",
        status: "Off-Plan",
        price: "From AED 3,200,000",
        beds: "3–5 Beds",
        baths: "3–5 Baths",
        size: "2,200–5,500 sqft",
        description: "Premium villas nestled within the award-winning Dubai Hills Estate, surrounded by championship golf greens.",
        highlights: ["Golf Course Views", "18-Hole Championship Golf", "Dubai Hills Mall nearby", "Gated community"],
      },
      {
        name: "Emaar Beachfront – Beach Vista",
        image: "/developers/emaar.jpeg",
        type: "Apartment",
        status: "Under Construction",
        price: "From AED 1,800,000",
        beds: "1–3 Beds",
        baths: "1–3 Baths",
        size: "600–1,900 sqft",
        description: "Seafront residences offering private beach access and panoramic views of the Arabian Gulf and Dubai Marina skyline.",
        highlights: ["Private Beach Access", "Marina & Sea Views", "Full amenities", "Premium finishes"],
      },
    ],
    contact: {
      email: "enquiry@emaar.ae",
      phone: "+97180036227",
      whatsapp: "+97180036227",
    },
  },
  {
    id: "damac-properties",
    name: "DAMAC Properties",
    coverImage: "/developers/damac.jpg",
    logo: "/developers/damac-logo.png",
    logoIsText: false,
    developer: "DAMAC Properties",
    location: "Dubai, UAE",
    description: "DAMAC Properties is a leading luxury real estate developer in the Middle East, delivering residential, commercial, and leisure properties across the region.",
    longDescription: "DAMAC Properties has been at the forefront of the Middle East's luxury real estate market since 2002. With a diverse portfolio spanning residential towers, golf communities, themed villa developments, and waterfront master plans, DAMAC has delivered over 46,000 homes across the UAE and internationally. Known for high-profile celebrity brand collaborations with names like Versace, Just Cavalli, and Paramount Hotels, DAMAC has carved out a unique niche in the ultra-luxury segment. Their landmark communities include DAMAC Hills, DAMAC Hills 2, DAMAC Lagoons, and DAMAC Bay by Cavalli.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/damac-properties",
    projects: [
      {
        name: "DAMAC Hills – Trump Villas",
        image: "/developers/damac.jpg",
        type: "Villa",
        status: "Ready",
        price: "From AED 2,800,000",
        beds: "3–6 Beds",
        baths: "3–6 Baths",
        size: "2,500–7,000 sqft",
        description: "Luxury villas surrounding Trump International Golf Club Dubai in DAMAC's flagship gated golf community.",
        highlights: ["Trump Golf Club", "Gated community", "Clubhouse & spa", "Strong rental demand"],
      },
      {
        name: "DAMAC Lagoons – Malta Cluster",
        image: "/developers/lagoos.jpg",
        type: "Townhouse",
        status: "Off-Plan",
        price: "From AED 1,600,000",
        beds: "3–5 Beds",
        baths: "3–4 Baths",
        size: "1,800–3,200 sqft",
        description: "Mediterranean-inspired townhouses in the Malta cluster of DAMAC Lagoons, featuring crystal lagoons and sandy beaches.",
        highlights: ["Crystal Lagoon Access", "Sandy beach", "Mediterranean theme", "Resort lifestyle"],
      },
      {
        name: "DAMAC Bay by Cavalli",
        image: "/developers/damac2.webp",
        type: "Apartment",
        status: "Off-Plan",
        price: "From AED 4,500,000",
        beds: "2–4 Beds",
        baths: "2–4 Baths",
        size: "1,200–4,500 sqft",
        description: "Ultra-luxury waterfront residences designed by Roberto Cavalli, offering bespoke interiors and Dubai Marina views.",
        highlights: ["Cavalli-designed interiors", "Dubai Harbour views", "Superyacht marina", "Ultra-luxury finish"],
      },
    ],
    contact: {
      email: "enquiry@damacgroup.com",
      phone: "+97180033326",
      whatsapp: "+97180033326",
    },
  },
  {
    id: "nakheel",
    name: "Nakheel",
    coverImage: "/developers/jvc.webp",
    logo: "/developers/nakheel-logo.png",
    logoIsText: false,
    developer: "Nakheel",
    location: "Dubai, UAE",
    description: "Nakheel is a Dubai government-owned developer and one of the world's largest, responsible for iconic developments including Palm Jumeirah and Jumeirah Village Circle.",
    longDescription: "Nakheel is one of the world's leading real estate developers and a key driver of Dubai's vision to create a truly global city. A Dubai Government-owned company, Nakheel has delivered some of the emirate's most iconic landmarks — including the Palm Jumeirah, The World Islands, Palm Jebel Ali, Jumeirah Village Circle, and Ibn Battuta Mall. Nakheel's portfolio spans master communities, retail destinations, hospitality assets, and waterfront developments, underpinning Dubai's transformation into one of the planet's most desirable addresses.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/nakheel",
    projects: [
      {
        name: "Palm Jumeirah – Garden Homes",
        image: "/developers/jvc.webp",
        type: "Villa",
        status: "Ready",
        price: "From AED 8,000,000",
        beds: "4–6 Beds",
        baths: "4–6 Baths",
        size: "4,000–8,000 sqft",
        description: "Exclusive beach villas on the fronds of Palm Jumeirah, offering private beach access and sweeping sea views.",
        highlights: ["Private beach", "Sea views on both sides", "Palm Jumeirah address", "Prestigious community"],
      },
      {
        name: "Jumeirah Village Circle – Canal Residences",
        image: "/developers/jvc.webp",
        type: "Apartment",
        status: "Ready",
        price: "From AED 550,000",
        beds: "Studio–3 Beds",
        baths: "1–3 Baths",
        size: "450–1,600 sqft",
        description: "Well-located apartments in JVC with easy access to major highways, parks, and retail facilities.",
        highlights: ["High rental yields", "Central location", "Affordable entry point", "Strong community"],
      },
      {
        name: "Palm Jebel Ali – Frond Villas",
        image: "/developers/downtown.jpeg",
        type: "Villa",
        status: "Off-Plan",
        price: "From AED 9,500,000",
        beds: "5–7 Beds",
        baths: "5–7 Baths",
        size: "5,500–12,000 sqft",
        description: "The next chapter of the Palm legacy — ultra-luxury beachfront villas on Dubai's largest palm island.",
        highlights: ["Largest palm island", "Private beachfront", "Historic launch prices", "Major capital appreciation expected"],
      },
    ],
    contact: {
      email: "customercare@nakheel.com",
      phone: "+97144088888",
      whatsapp: "+97144088888",
    },
  },
  {
    id: "sobha-realty",
    name: "Sobha Realty",
    coverImage: "/developers/sobha.jpeg",
    logo: "/developers/sobha-logo.png",
    logoIsText: false,
    developer: "Sobha Realty",
    location: "MBR City, Dubai",
    description: "Sobha Realty is a premium luxury developer renowned for its unique backward integration model, delivering exceptional quality across every aspect of its projects.",
    longDescription: "Sobha Realty is a premium luxury real estate developer renowned for its unique backward integration model — where every element, from design and engineering to construction and interiors, is handled in-house. This results in exceptional quality control and some of the finest finishes available in Dubai. Founded by PNC Menon, Sobha's flagship communities — Sobha Hartland in MBR City and the upcoming Sobha Hartland 2 — offer waterfront living, lush greenery, and top-tier schools within beautifully master-planned neighbourhoods. Sobha is consistently rated among Dubai's most trusted luxury developers.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/sobha-realty",
    projects: [
      {
        name: "Sobha Hartland – Forest Villas",
        image: "/developers/sobha.jpeg",
        type: "Villa",
        status: "Ready",
        price: "From AED 5,500,000",
        beds: "4–6 Beds",
        baths: "4–5 Baths",
        size: "4,000–8,000 sqft",
        description: "Standalone villas surrounded by lush forests in Sobha Hartland, moments from Downtown Dubai with canal frontage.",
        highlights: ["Canal-facing plots", "Forest greenery", "Backward-integrated quality", "Near Downtown"],
      },
      {
        name: "Sobha Creek Vistas Heights",
        image: "/developers/soba2.webp",
        type: "Apartment",
        status: "Off-Plan",
        price: "From AED 1,100,000",
        beds: "1–3 Beds",
        baths: "1–3 Baths",
        size: "550–1,800 sqft",
        description: "High-rise twin towers offering panoramic views of the Dubai skyline, Creek, and Hartland greenery.",
        highlights: ["Panoramic skyline views", "Premium Sobha quality", "MBR City address", "High appreciation"],
      },
    ],
    contact: {
      email: "enquiry@sobharealty.com",
      phone: "+97180076242",
      whatsapp: "+97180076242",
    },
  },
  {
    id: "binghatti-developers",
    name: "Binghatti Developers",
    coverImage: "/developers/dubaicreek.jpeg",
    logo: "/developers/binghatti-logo.png",
    logoIsText: false,
    developer: "Binghatti Developers",
    location: "Dubai, UAE",
    description: "Binghatti is one of Dubai's fastest-growing developers, known for architecturally bold residential towers with distinctive angular facades and quick delivery timelines.",
    longDescription: "Binghatti Developers has rapidly emerged as one of Dubai's most prolific and design-forward real estate companies. Recognized for their architecturally distinctive buildings featuring bold angular facades inspired by the flow of water, Binghatti has carved a unique niche in the mid-to-luxury segment. With a remarkable track record for on-time — and often ahead of schedule — project delivery, Binghatti has earned strong investor trust. Their high-profile collaborations include Bugatti Residences and Mercedes-Benz Places, showcasing their ambition in the ultra-luxury space.",
    propertyTypes: ["Apartments", "Penthouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High ROI"],
    href: "/developers/binghatti-developers",
    projects: [
      {
        name: "Bugatti Residences",
        image: "/developers/dubaicreek.jpeg",
        type: "Penthouse",
        status: "Off-Plan",
        price: "From AED 52,000,000",
        beds: "4–7 Beds",
        baths: "4–7 Baths",
        size: "8,000–24,000 sqft",
        description: "The world's first Bugatti-branded residential development, featuring hydrodynamic architecture and bespoke supercar-inspired interiors.",
        highlights: ["World first Bugatti-branded", "Supercar-inspired design", "Concierge & valet", "Ultra-premium"],
      },
      {
        name: "Binghatti Orchid – JVC",
        image: "/developers/jvc.webp",
        type: "Apartment",
        status: "Ready",
        price: "From AED 650,000",
        beds: "Studio–2 Beds",
        baths: "1–2 Baths",
        size: "400–1,200 sqft",
        description: "A bold residential tower in Jumeirah Village Circle offering strong rental returns and distinctive Binghatti architecture.",
        highlights: ["JVC central location", "Signature architecture", "High rental yield", "Ready to move in"],
      },
    ],
    contact: {
      email: "info@binghatti.com",
      phone: "+97144060800",
      whatsapp: "+97144060800",
    },
  },
  {
    id: "danube-properties",
    name: "Danube Properties",
    coverImage: "/developers/dubaisportcity.webp",
    logo: "/developers/danube-logo.png",
    logoIsText: false,
    developer: "Danube Properties",
    location: "Dubai, UAE",
    description: "Danube Properties is a leading affordable luxury developer in Dubai, known for its 1% monthly payment plan and investor-friendly pricing.",
    longDescription: "Danube Properties has democratized luxury living in Dubai with its innovative 1% monthly payment plan, making homeownership accessible to a broad spectrum of buyers and investors. Founded by the Danube Group, one of the Middle East's largest building materials traders, the developer benefits from deep supply chain advantages that keep costs competitive without compromising quality. Danube has delivered a wide range of projects across Dubai Silicon Oasis, Arjan, Business Bay, and Al Furjan, consistently offering superior amenities and finishes at below-market price points.",
    propertyTypes: ["Apartments", "Studios"],
    marketPosition: ["Affordable Luxury", "1% Payment Plan", "Investor Friendly"],
    href: "/developers/danube-properties",
    projects: [
      {
        name: "Danube Oceanz – Dubai Maritime City",
        image: "/developers/dubaisportcity.webp",
        type: "Apartment",
        status: "Off-Plan",
        price: "From AED 950,000",
        beds: "Studio–3 Beds",
        baths: "1–3 Baths",
        size: "400–1,800 sqft",
        description: "Waterfront tower in Dubai Maritime City with sea views, infinity pool, and Danube's signature 1% monthly payment plan.",
        highlights: ["Waterfront location", "1% payment plan", "Sea views", "Infinity pool"],
      },
      {
        name: "Danube Sportz – Dubai Sports City",
        image: "/developers/dubaisportcity.webp",
        type: "Apartment",
        status: "Ready",
        price: "From AED 600,000",
        beds: "Studio–2 Beds",
        baths: "1–2 Baths",
        size: "370–1,100 sqft",
        description: "A sports-themed residential tower offering a basketball court, batting cages, and tennis within the community.",
        highlights: ["Sports facilities on site", "Affordable entry", "Strong yields", "Dubai Sports City"],
      },
    ],
    contact: {
      email: "enquiry@danubeproperties.com",
      phone: "+97144188000",
      whatsapp: "+97144188000",
    },
  },
  {
    id: "meraas",
    name: "Meraas",
    coverImage: "/developers/dubaihills.jpeg",
    logo: "/developers/Meraas-logo.svg",
    logoIsText: false,
    developer: "Meraas",
    location: "Dubai, UAE",
    description: "Meraas is a Dubai-based holding company developing lifestyle, retail, and residential destinations that enrich community living across the emirate.",
    longDescription: "Meraas is a leading Dubai-based developer and lifestyle destination creator, responsible for transforming some of Dubai's most vibrant neighbourhoods. From Bluewaters Island — home of Ain Dubai, the world's largest observation wheel — to City Walk, La Mer, and Nikki Beach Resort & Spa, Meraas has established a reputation for creating immersive, lifestyle-focused destinations. Their residential portfolio integrates seamlessly with retail, dining, and entertainment, making Meraas communities among the most sought-after addresses in Dubai.",
    propertyTypes: ["Apartments", "Townhouses", "Villas"],
    marketPosition: ["Lifestyle Destinations", "Freehold", "Premium"],
    href: "/developers/meraas",
    projects: [
      {
        name: "Bluewaters Island Residences",
        image: "/developers/dubaihills.jpeg",
        type: "Apartment",
        status: "Ready",
        price: "From AED 3,000,000",
        beds: "1–4 Beds",
        baths: "1–4 Baths",
        size: "800–4,200 sqft",
        description: "Exclusive residences on Bluewaters Island, steps from Ain Dubai and the island's vibrant dining and retail promenade.",
        highlights: ["Steps from Ain Dubai", "Island living", "Premium address", "Marina views"],
      },
      {
        name: "City Walk Residences",
        image: "/developers/arjan.jpg",
        type: "Apartment",
        status: "Ready",
        price: "From AED 2,200,000",
        beds: "1–3 Beds",
        baths: "1–3 Baths",
        size: "700–2,500 sqft",
        description: "Contemporary residences above City Walk, Dubai's premier open-air lifestyle destination.",
        highlights: ["Above City Walk retail", "Al Wasl Road", "Premium finishes", "Lifestyle destination"],
      },
    ],
    contact: {
      email: "enquiry@meraas.ae",
      phone: "+97144088000",
      whatsapp: "+97144088000",
    },
  },
  {
    id: "ellington-properties",
    name: "Ellington Properties",
    coverImage: "/developers/meydan.jpg",
    logo: "/developers/ellington-logo.png",
    logoIsText: false,
    developer: "Ellington Properties",
    location: "Dubai, UAE",
    description: "Ellington Properties is a design-led luxury developer in Dubai, creating carefully curated boutique residences that prioritize artful living.",
    longDescription: "Ellington Properties is a design-first luxury developer that has quickly established itself as Dubai's premier boutique residential brand. Every Ellington project is a carefully curated statement of art and architecture, drawing on global design influences to deliver residences that are visually distinctive and exceptionally liveable. With projects across Business Bay, JVC, Palm Jumeirah, and Downtown Dubai, Ellington appeals to discerning buyers who value design integrity, quality craftsmanship, and attention to detail over scale. Their approach has earned them consistent recognition in Dubai's luxury segment.",
    propertyTypes: ["Apartments", "Penthouses", "Villas"],
    marketPosition: ["Design-Led", "Boutique Luxury", "Freehold"],
    href: "/developers/ellington-properties",
    projects: [
      {
        name: "Ellington House – Dubai Hills Estate",
        image: "/developers/meydan.jpg",
        type: "Apartment",
        status: "Ready",
        price: "From AED 1,400,000",
        beds: "1–3 Beds",
        baths: "1–3 Baths",
        size: "650–2,200 sqft",
        description: "Design-forward residences in Dubai Hills Estate with curated interiors, a rooftop terrace, and proximity to Dubai Hills Mall.",
        highlights: ["Award-winning design", "Rooftop infinity pool", "Dubai Hills Mall", "Boutique scale"],
      },
      {
        name: "The Crestmark – Business Bay",
        image: "/developers/mayden.jpg",
        type: "Apartment",
        status: "Off-Plan",
        price: "From AED 1,200,000",
        beds: "1–2 Beds",
        baths: "1–2 Baths",
        size: "600–1,400 sqft",
        description: "An architecturally striking waterfront tower in Business Bay with canal views and art-inspired interiors.",
        highlights: ["Canal frontage", "Art-inspired interiors", "Business Bay", "Premium facilities"],
      },
    ],
    contact: {
      email: "info@ellingtonproperties.com",
      phone: "+97144063232",
      whatsapp: "+97144063232",
    },
  },
  {
    id: "azizi-developments",
    name: "Azizi Developments",
    coverImage: "/developers/azizi.jpeg",
    logo: "/developers/azizi-logo.png",
    logoIsText: false,
    developer: "Azizi Developments",
    location: "Dubai, UAE",
    description: "Azizi Developments is one of Dubai's leading private real estate developers, delivering high-quality residential and mixed-use projects across key districts.",
    longDescription: "Azizi Developments is one of Dubai's most active private developers, having delivered over 11,000 units since 2007 across key districts including Meydan, Palm Jumeirah, Al Furjan, Studio City, and Dubai South. Known for consistent quality, accessible pricing, and strong investor returns, Azizi has positioned itself as a reliable partner for both end-users and investors. Their flagship developments — Azizi Riviera and Azizi Venice — represent two of Dubai's most ambitious master-planned waterfront communities.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "High Rental Demand"],
    href: "/developers/azizi-developments",
    projects: [
      {
        name: "Azizi Riviera – Phase 4",
        image: "/developers/azizi.jpeg",
        type: "Apartment",
        status: "Ready",
        price: "From AED 700,000",
        beds: "Studio–3 Beds",
        baths: "1–3 Baths",
        size: "380–1,700 sqft",
        description: "The latest phase of the French-Mediterranean inspired Azizi Riviera master development in Meydan.",
        highlights: ["Crystal lagoon", "Retail boulevard", "Meydan location", "Strong yields"],
      },
      {
        name: "Azizi Venice – Lagoon Residences",
        image: "/developers/azizivenice.webp",
        type: "Apartment",
        status: "Off-Plan",
        price: "From AED 850,000",
        beds: "Studio–3 Beds",
        baths: "1–3 Baths",
        size: "400–2,000 sqft",
        description: "Inspired by Venice, Italy — featuring the largest crystal lagoon in Dubai, surrounded by towers, retail, and a boulevard.",
        highlights: ["18km Crystal Lagoon", "Near Al Maktoum Airport", "Venice-inspired theme", "Expo City proximity"],
      },
    ],
    contact: {
      email: "info@azizidevelopments.com",
      phone: "+97144096444",
      whatsapp: "+97144096444",
    },
  },
  {
    id: "select-group",
    name: "Select Group",
    coverImage: "/developers/dubaicreek.jpeg",
    logo: "/developers/select-logo.png",
    logoIsText: false,
    developer: "Select Group",
    location: "Dubai Marina, UAE",
    description: "Select Group is a prominent Dubai developer with an extensive residential portfolio across Dubai Marina and Business Bay, known for delivering premium waterfront living.",
    longDescription: "Select Group has established a strong presence in Dubai's premium real estate market, particularly within Dubai Marina and Business Bay. With a diverse portfolio exceeding AED 15 billion in gross development value, Select Group is behind landmark projects including Marina Gate, Peninsula, 15 Northside, and 6 Senses Residences. Known for consistent quality and well-chosen locations, Select Group appeals to investors and high-net-worth buyers seeking premium waterfront and urban residences in Dubai's most coveted corridors.",
    propertyTypes: ["Apartments", "Penthouses"],
    marketPosition: ["Premium Waterfront", "Freehold", "Investor Friendly"],
    href: "/developers/select-group",
    projects: [
      {
        name: "6 Senses Residences – Palm Jumeirah",
        image: "/developers/dubaicreek.jpeg",
        type: "Penthouse",
        status: "Off-Plan",
        price: "From AED 18,000,000",
        beds: "2–5 Beds",
        baths: "2–5 Baths",
        size: "2,500–14,000 sqft",
        description: "The world's first 6 Senses-branded residences, offering wellness-centric living on the iconic Palm Jumeirah.",
        highlights: ["6 Senses branded", "Wellness architecture", "Palm Jumeirah", "Ultra-luxury"],
      },
      {
        name: "Marina Gate Tower 1",
        image: "/developers/al.jpg",
        type: "Apartment",
        status: "Ready",
        price: "From AED 1,300,000",
        beds: "1–3 Beds",
        baths: "1–3 Baths",
        size: "700–2,800 sqft",
        description: "A striking high-rise in Dubai Marina offering Marina Walk frontage, infinity pools, and panoramic sea views.",
        highlights: ["Marina Walk frontage", "Panoramic sea views", "5-star amenities", "Strong rental yields"],
      },
    ],
    contact: {
      email: "info@selectgroup.ae",
      phone: "+97144536666",
      whatsapp: "+97144536666",
    },
  },
  {
    id: "majid-al-futtaim",
    name: "Majid Al Futtaim",
    coverImage: "/developers/dubaihills.jpeg",
    logo: "/developers/maf-logo.png",
    logoIsText: false,
    developer: "Majid Al Futtaim",
    location: "Dubai, UAE",
    description: "Majid Al Futtaim is a leading shopping mall, communities, retail, and leisure pioneer across the Middle East, with Tilal Al Ghaf as its flagship master community.",
    longDescription: "Majid Al Futtaim is one of the region's most influential and diversified conglomerates, best known for developing Malls of the Emirates and City Centres across the GCC. Their real estate communities arm has created Tilal Al Ghaf — one of Dubai's most ambitious and sustainable master-planned communities — featuring a stunning 70,000 sqm lagoon, beachfront villas, townhouses, and a rich retail and community hub. Built around the principles of wellbeing, connectivity, and environmental harmony, Tilal Al Ghaf represents the future of community living in Dubai.",
    propertyTypes: ["Villas", "Townhouses", "Apartments"],
    marketPosition: ["Sustainable Living", "Freehold", "High Demand"],
    href: "/developers/majid-al-futtaim",
    projects: [
      {
        name: "Tilal Al Ghaf – Serenity Mansions",
        image: "/developers/dubaihills.jpeg",
        type: "Villa",
        status: "Off-Plan",
        price: "From AED 12,000,000",
        beds: "5–7 Beds",
        baths: "5–7 Baths",
        size: "8,000–16,000 sqft",
        description: "Lakefront mansions within Tilal Al Ghaf offering the pinnacle of sustainable luxury living with direct lagoon access.",
        highlights: ["Direct lagoon access", "Sustainable design", "Community clubhouse", "Top-tier schools nearby"],
      },
      {
        name: "Tilal Al Ghaf – Aura Townhouses",
        image: "/developers/valley.jpg",
        type: "Townhouse",
        status: "Ready",
        price: "From AED 2,500,000",
        beds: "4–5 Beds",
        baths: "4–5 Baths",
        size: "2,800–4,200 sqft",
        description: "Family townhouses in Tilal Al Ghaf with lagoon beach access, parks, and cycling tracks just minutes from the city.",
        highlights: ["Lagoon beach access", "Cycling & jogging tracks", "Retail village", "Family-oriented"],
      },
    ],
    contact: {
      email: "enquiry@maf.ae",
      phone: "+97180060520",
      whatsapp: "+97180060520",
    },
  },
  {
    id: "dubai-properties",
    name: "Dubai Properties",
    coverImage: "/developers/dubaisportcity.webp",
    logo: "/developers/dubai-properties-logo.png",
    logoIsText: false,
    developer: "Dubai Properties",
    location: "Dubai, UAE",
    description: "Dubai Properties is a leading master developer and asset manager with a portfolio of residential, commercial, and retail projects across Dubai.",
    longDescription: "Dubai Properties is a leading master developer and real estate asset manager with a broad portfolio spanning residential communities, commercial towers, and retail destinations across Dubai. As part of Dubai Holding, one of the emirate's largest conglomerates, Dubai Properties benefits from strong government backing and a deep strategic vision. Their developments include Jumeirah Beach Residence (JBR) — one of the world's largest single-phase residential complexes — as well as Business Bay, Villanova, Serena, and La Rosa at Villanova, catering to a wide spectrum of buyers across different price points.",
    propertyTypes: ["Apartments", "Villas", "Townhouses"],
    marketPosition: ["Freehold", "Investor Friendly", "Family Communities"],
    href: "/developers/dubai-properties",
    projects: [
      {
        name: "Jumeirah Beach Residence – JBR",
        image: "/developers/dubaisportcity.webp",
        type: "Apartment",
        status: "Ready",
        price: "From AED 1,500,000",
        beds: "1–4 Beds",
        baths: "1–4 Baths",
        size: "700–3,500 sqft",
        description: "One of Dubai's most iconic beachfront communities — a vibrant destination with direct beach access, The Walk, and The Beach retail.",
        highlights: ["Beachfront access", "The Walk promenade", "Vibrant community", "Strong rental returns"],
      },
      {
        name: "Villanova – La Rosa",
        image: "/developers/valley.jpg",
        type: "Townhouse",
        status: "Ready",
        price: "From AED 1,400,000",
        beds: "3–4 Beds",
        baths: "3–4 Baths",
        size: "1,600–2,500 sqft",
        description: "Spanish-inspired townhouses at Villanova with schools, parks, and community retail in a family-friendly setting.",
        highlights: ["Spanish-inspired design", "Family-friendly", "Schools nearby", "Dubai-Al Ain Road"],
      },
    ],
    contact: {
      email: "enquiry@dubaiproperties.ae",
      phone: "+97144232323",
      whatsapp: "+97144232323",
    },
  },
];

export function getDeveloperBySlug(slug: string): Developer | undefined {
  return developers.find((d) => d.id === slug);
}